# Generated by Django 5.2.1 on 2026-06-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(blank=True, max_length=40)),
                ('notify_sms', models.BooleanField(default=True)),
                ('notify_wechat', models.BooleanField(default=False)),
                ('notify_app', models.BooleanField(default=False)),
                ('wechat_id', models.CharField(blank=True, max_length=100)),
                ('app_user_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
